import {SpriteBase64} from "../sprite.js";

export const spriteBoostBar = new SpriteBase64("iVBORw0KGgoAAAANSUhEUgAAAH4AAAAcAQMAAACd0ZmaAAAABlBMVEUAAAD///+l2Z/dAAAACXBIWXMAAAsSAAALEgHS3X78AAAAMUlEQVQY02Ow/48CPjDUowr8YPjAgAJsGB6gCsgwHEAV4BkVoFwAI5AxogEjotCjEgAQclFV3qUXFgAAAABJRU5ErkJggg==", 0, 0);
