import {SpriteBase64} from "../sprite.js";

export const spriteBoostPip = new SpriteBase64("iVBORw0KGgoAAAANSUhEUgAAAAoAAAAUAQMAAACOID4VAAAABlBMVEUAAAD///+l2Z/dAAAACXBIWXMAAAsSAAALEgHS3X78AAAAF0lEQVQI12OQY2CobwCh/weIRRD1cgwAXiocq2Xlx08AAAAASUVORK5CYII=", 0, 0);
