import {SpriteBase64} from "../sprite.js";

export const spriteRobinVertical = new SpriteBase64("iVBORw0KGgoAAAANSUhEUgAAAB4AAAAZAQMAAAAc+wxZAAAABlBMVEUAAAD///+l2Z/dAAAACXBIWXMAAAsSAAALEgHS3X78AAAAUElEQVQI12NgYGYAAvYGGMF/AEbIP2BgqLH/8IPhX/3PPwz1////YLD///8DhPX//39kMQQhW//rAQOH/AMHBgY5oAEMPAdgBO8BFDtYGhgAfZ0tyrhpqgsAAAAASUVORK5CYII=", 16, 9);
