import {SpriteBase64} from "../sprite.js";

export const spriteRobinHorizontal = new SpriteBase64("iVBORw0KGgoAAAANSUhEUgAAACIAAAASAQMAAAAE854sAAAABlBMVEUAAAD///+l2Z/dAAAACXBIWXMAAAsSAAALEgHS3X78AAAAUElEQVQI1x2MsQ2AQAwDI1GkgwWQWIPuF0OC0RiFESi/eHHYiZQrzrIjIp/QLa+5dbMVGcLE5xAuabgD7E/opdVK8EJTqAFczcOcjViLu/4HJKUfCzeOqUwAAAAASUVORK5CYII=", 16, 9);
