import {SpriteBase64} from "../sprite.js";

export const spriteTree1 = new SpriteBase64("iVBORw0KGgoAAAANSUhEUgAAABIAAAAjAQMAAACjJsgcAAAABlBMVEUAAAD///+l2Z/dAAAACXBIWXMAAAsSAAALEgHS3X78AAAAN0lEQVQI12NgOMDAAMOMDxCY+QMCs/9AYP4/CCz/D4Ht/yNw/f8GOP7//wAch/9qAJuHbA8SBgCtlisq2gL0WAAAAABJRU5ErkJggg==", 9, 35);
